name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test (Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails_version }})
    runs-on: ubuntu-${{ matrix.ubuntu }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2', '3.3',  jruby-9.4, jruby-head, ruby-head]
        rails_version:
          - '7.0.0'
          - '7.1.0'
          - '7.2.0'
          - '8.0.0'
          - 'edge'
        ubuntu: [latest]
        include:
          # Ruby 2.6
          - ruby: 2.6
            rails_version: '6.0.0'
            ubuntu: '20.04'
          - ruby: 2.6
            rails_version: '6.1.0'
            ubuntu: '20.04'

          # ruby 3.1 (Dropped by Rails 8)
          - ruby: 3.1
            rails_version: '7.0.0'
            ubuntu: 'latest'
          - ruby: 3.1
            rails_version: '7.1.0'
            ubuntu: 'latest'
          - ruby: 3.1
            rails_version: '7.2.0'
            ubuntu: 'latest'

          # jruby-9.2
          - ruby: jruby-9.2
            rails_version: '6.0.0'
            ubuntu: '20.04'
          - ruby: jruby-9.2
            rails_version: '6.1.0'
            ubuntu: '20.04'

          #
          # The past
          #
          # EOL Active Record
          - ruby: 2.2
            rails_version: '3.2.0'
            ubuntu: '20.04'
          - ruby: 2.1
            rails_version: '4.1.0'
            ubuntu: '20.04'
          - ruby: 2.4
            rails_version: '4.2.0'
            ubuntu: '20.04'
          - ruby: 2.4
            rails_version: '5.0.0'
            ubuntu: '20.04'
          - ruby: 2.5
            rails_version: '5.1.0'
            ubuntu: '20.04'
          - ruby: 2.6
            rails_version: '5.2.0'
            ubuntu: '20.04'
          - ruby: 2.7
            rails_version: '5.2.0'
            ubuntu: '22.04'
          - ruby: jruby-9.2
            rails_version: '5.2.0'
            ubuntu: '22.04'
          - ruby: 2.7
            rails_version: '6.0.0'
            ubuntu: '22.04'
          - ruby: 3.0
            rails_version: '6.0.0'
            ubuntu: '22.04'
          - ruby: 3.2
            rails_version: '6.0.0'
            ubuntu: '22.04'
          - ruby: jruby-9.4
            rails_version: '6.0.0'
            ubuntu: '22.04'
          - ruby: 2.7
            rails_version: '6.1.0'
            ubuntu: '22.04'
          - ruby: 3.0
            rails_version: '6.1.0'
            ubuntu: '22.04'
          - ruby: 3.2
            rails_version: '6.1.0'
            ubuntu: '22.04'
          - ruby: jruby-9.4
            rails_version: '6.0.0'
            ubuntu: '22.04'
          - ruby: 2.7
            rails_version: '7.0.0'
            ubuntu: '22.04'
          - ruby: 3.0
            rails_version: '7.0.0'
            ubuntu: '22.04'
          - ruby: jruby-9.4
            rails_version: '6.0.0'
            ubuntu: '22.04'
          
          # EOL Ruby
          - ruby: 2.7
            rails_version: '7.1.0'
            ubuntu: '22.04'
          - ruby: 3.0
            rails_version: '7.1.0'
            ubuntu: '22.04'

    continue-on-error: ${{ matrix.rails_version == 'edge' || endsWith(matrix.ruby, 'head') }}

    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
      run: bundle exec rspec
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@main
      with:
        github-token: ${{ secrets.github_token }}
        flag-name: run-${{ matrix.ruby }}-${{ matrix.rails_version }}
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@main
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
